### ISSUE TITLE
Link topics and replies to discourse

### ISSUE THREAD

**Issue by audreyt** [g0v/vtaiwan.tw#1]
Topic ID 可以從 Topic name （如「股權模式或債權模式？」）由 `fancy_title` 取得：
https://cors.vtaiwan.tw/c/6-category.json
Replies 可以從 Topic ID 取得：
https://cors.vtaiwan.tw/t/topic/21.json

**Comment by audreyt** [comment]
目前 @soidid 已實作完成並上線 :rainbow: 

有一個小問題：從首頁按到目錄，再按到 https://vtaiwan.tw/#!/closelyheld/1 會有一陣子頁面空白。
也許可以從首頁和目錄頁時就預先載入 json 資源？

**Comment by yhsiang** [comment]
預載 by 8e37fc7232f1cc023fd0cd357710e56d40c33d0a
