### ISSUE TITLE
Reset scroll position after `go()`

### ISSUE THREAD

**Issue by audreyt** [g0v/vtaiwan.tw#10]
Currently in mobile phone if we scroll down to click 了解更多, then scroll down to click 如何發言, sometimes the scrolling position is not updated.

I attempted a fix in https://github.com/g0v/vtaiwan.tw/blob/gh-pages/mockup/app.js#L274 but perhaps 100ms is too short, and there may be a way to hook into `$location` transition completion that does not require `setTimeout`.

Similar issues exist when clicked on second-level item in a book outline; scrolling and/or highlight the clicked item would be great.

**Comment by audreyt** [comment]
Strangely, setting `$('body').scrollTop()` had no effect. Perhaps workaround this by setting an empty div on top and `scrollIntoView` it?

**Comment by ghost** [comment]
發現造成另外一個 bug XD，處理中

**Comment by ghost** [comment]
fixed by 3b95525e and 78a9af20
