### ISSUE TITLE
some lexicon position still be weird

### ISSUE THREAD

**Issue by yhsiang** [g0v/vtaiwan.tw#14]
![2015-01-13 9 26 11](https://cloud.githubusercontent.com/assets/93509/5721313/0be9a60e-9b6b-11e4-84a1-4b903d97b550.png)

same as https://github.com/pm5/gitbook-plugin-lexicon/issues/6

**Comment by yhsiang** [comment]
:sos:  @muan , can you help to take a look at this ?

**Comment by muan** [comment]
Got a URL?

**Comment by audreyt** [comment]
https://closelyheld.vtaiwan.tw/ ( src: https://github.com/g0v/closelyheld-gitbook/tree/gh-pages )

To reproduce, adjust the screen width so that an underlined text (lexicon item) is broken across two lines.

**Comment by audreyt** [comment]
e.g. in the homepage of that gitbook hovering on「有限」:

 ![2015-01-13 9 53 16](https://cloud.githubusercontent.com/assets/20723/5721612/a9937198-9b6e-11e4-8a78-c283656ed026.png)

One workaround may be forcing non-break for all lexicon items? Perhaps there's a more elegant fix...

**Comment by muan** [comment]
Adding `top: 0` to `.hint:hover:after` should fix the separated arrow problem, unfortunately the tooltip will be cutoff regardless. Would've send a pull request but I'm not sure where the real source of `lexicon.css` is.

**Comment by audreyt** [comment]
Wow, awesome! The real source is here: https://github.com/pm5/gitbook-plugin-lexicon/blob/master/book/lexicon.css

**Comment by yhsiang** [comment]
:rainbow:

**Comment by pm5** [comment]
awesome!
