### ISSUE TITLE
Initial clicking of nav bar is empty

### ISSUE THREAD

**Issue by audreyt** [g0v/vtaiwan.tw#17]
Clicking the left angle restores the correct menu.

![2015-01-16 6 06 09](https://cloud.githubusercontent.com/assets/20723/5774591/6afddbd8-9daa-11e4-88d6-eb24ed61afa1.png)

**Comment by pm5** [comment]
Revert it.  Something bad happened...

**Comment by pm5** [comment]
Okay, dirty fix again.
