### ISSUE TITLE
second-level menu icon position

### ISSUE THREAD

**Issue by yhsiang** [g0v/vtaiwan.tw#2]
![2015-01-07 1 44 55](https://cloud.githubusercontent.com/assets/93509/5633101/0b70bfd4-960f-11e4-9a9a-a7f347cab720.png)

make left-arrow vertical-align with hamburger icon will be better ?

**Comment by ghost** [comment]
fixed by 1da447d062
![2015-01-13 11 48 15](https://cloud.githubusercontent.com/assets/3395905/5715775/27928732-9b1a-11e4-9fc6-030cfa59c5d9.png)

**Comment by yhsiang** [comment]
:+1:
