### ISSUE TITLE
mailto: is broken

### ISSUE THREAD

**Issue by clkao** [g0v/vtaiwan.tw#21]
the mailbox icons in https://vtaiwan.tw/#!/crowdfunding/2/20

**Comment by audreyt** [comment]
Meant to mail to user-specified recipients as a way of sharing, not as
reply, iirc... Could be more specific
2015/1/20 下午7:46 於 "Chia-liang Kao" notifications@github.com 寫道：

**Comment by clkao** [comment]
maybe a more generic share button for individual permalink?

**Comment by yhsiang** [comment]
individual permalink is better, but maybe it needs a pop window like origin discourse.
@soidid  can help to do this? 
![2015-01-13 2 54 54](https://cloud.githubusercontent.com/assets/93509/5718689/84ae1d4c-9b4b-11e4-9d89-7a19a47a4e89.png)
four icons aren't needed in the bottom

**Comment by ghost** [comment]
可以噢，我來試試看

**Comment by yhsiang** [comment]
:+1: :smile_cat:

**Comment by ghost** [comment]
demo: https://demo.vtaiwan.tw/mockup/#/crowdfunding/2/20

![2015-01-27 16 18 09](https://cloud.githubusercontent.com/assets/3395905/5915385/423d9852-a640-11e4-8407-37c80a4b9f89.png)

@yhsiang 
這樣？

**Comment by ghost** [comment]
手機上我要再調一下

**Comment by ghost** [comment]
<img src="https://cloud.githubusercontent.com/assets/3395905/5915688/9a117370-a643-11e4-93dd-5da5387c676f.png" width="300px">
手機版本做這樣？

**Comment by yhsiang** [comment]
:+1:

**Comment by ghost** [comment]
不過 code 有點不美，為了 css 計算位置的方便性而 duplicate template
可能不是最好的解法

**Comment by yhsiang** [comment]
6a5116bdf40cdc5a7b986f3e52db8bfd91662d03
b901b226b6639c7f1c19ee525d9227918901c5d8
merged to master
