### ISSUE TITLE
標注提案方 logo/id

### ISSUE THREAD

**Issue by audreyt** [g0v/vtaiwan.tw#25]
考慮到 talk.vtaiwan.tw 會由提案方七天內用機關帳號直接回覆，也許可以在 proposals 裡每個提案的右上角放機關的 icon，如果寬度足夠的話也顯示機關 id (例如 `@fsc` 是金管會、`@moea` 是經濟部、`@mof` 是財政部)，這樣大家比較知道要 @ 誰？

<img src="http://upload.wikimedia.org/wikipedia/zh/c/c9/Financial_supervisory_commission_logo.gif" width="256">

<img src="https://upload.wikimedia.org/wikipedia/zh/thumb/4/43/Ministry_of_Economic_Affairs.svg/400px-Ministry_of_Economic_Affairs.svg.png" width="256">

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/ROC_Ministry_of_Finance_Seal.svg/627px-ROC_Ministry_of_Finance_Seal.svg.png" width="256">

**Comment by ghost** [comment]
群眾募資：金管會
閉鎖型公司：經濟部
網路交易課稅：財政部

**Comment by ghost** [comment]
https://demo.vtaiwan.tw/mockup/#/proposals
因為下面有進度條，覺得加上 logo 好像會太花～？

等到三個部會都有帳號，把 @{abbr} 連到 discourse 的界面？
https://talk.vtaiwan.tw/users/{abbr}/activity

**Comment by audreyt** [comment]
提案三的提案方有帳號了:  [MOFTA](https://talk.vtaiwan.tw/users/mofta) 財政部賦稅署。

**Comment by audreyt** [comment]
提案一的提案方有帳號了:  [sfb](https://talk.vtaiwan.tw/users/sfb) 金管會證期局。
已更新 https://vtaiwan.tw/#!/proposals 頁面。
