### ISSUE TITLE
Styling need to reduce spaces

### ISSUE THREAD

**Issue by audreyt** [g0v/vtaiwan.tw#3]
compare e.g. https://vtaiwan.tw/#!/closelyheld/2/56 vs the discourse version

**Comment by muan** [comment]
Looks like it's sort of already fixed on `gh-pages`. 
https://demo.vtaiwan.tw/mockup/#/closelyheld/2/56 vs https://vtaiwan.tw/#!/closelyheld/2/56
I'll hold my fire then.

**Comment by audreyt** [comment]
There's quite a few overpadding/overmargin though (body font size increase is intentional)...

Perhaps `word-wrap: break-word` would help?

Compare demo (expand the circle on https://demo.vtaiwan.tw/mockup/#/closelyheld/2/56  to see):

![2015-01-11 4 28 22](https://cloud.githubusercontent.com/assets/20723/5694682/e3a9e6da-99ae-11e4-8286-543025793b70.png)

and discourse:

![2015-01-11 4 29 08](https://cloud.githubusercontent.com/assets/20723/5694684/06141204-99af-11e4-891e-1c4a078a71b2.png)

Also Jalin's blockquote styling in https://demo.vtaiwan.tw/mockup/#/closelyheld/2/59 :

![2015-01-11 4 35 42](https://cloud.githubusercontent.com/assets/20723/5694699/eb668f26-99af-11e4-8f4f-54534c891248.png)

and discouse ( https://talk.vtaiwan.tw/t/topic/59/5 ):

![2015-01-11 4 30 21](https://cloud.githubusercontent.com/assets/20723/5694687/2d1934e2-99af-11e4-959c-64270f4ba0a4.png)

**Comment by yhsiang** [comment]
I merged soidid's previous work to `master`
