### ISSUE TITLE
Topics with more than 20 replies don't show up

### ISSUE THREAD

**Issue by audreyt** [g0v/vtaiwan.tw#33]
As reported by @clkao, last reply displayed in https://vtaiwan.tw/#!/etax/2/100 is Feb 7 due to paging restrictions in the discourse API.

The root cause, as explained in in https://meta.discourse.org/t/discourse-api-documentation/22706/16 seems to mean we need a loop around https://github.com/g0v/vtaiwan.tw/blob/gh-pages/mockup/app.js#L318 that looks at 
https://talk.vtaiwan.tw/t/100.json with `"highest_post_number":29` and fetch https://talk.vtaiwan.tw/t/100/20.json (and `40.json` etc, if needed) iteratively.

**Comment by clkao** [comment]
isn't it easier to add configurable limit in the api endpoint?

**Comment by audreyt** [comment]
Indeed — I haven't found one in https://github.com/discourse/discourse/blob/master/config/site_settings.yml though
