### ISSUE TITLE
閉鎖型公司頁面問題

### ISSUE THREAD

**Issue by nchild** [g0v/vtaiwan.tw#39]
點擊閉鎖型公司連結，會先停在空白 menu，然後再點一下，會發現 html 外露的標題。
https://vtaiwan.tw/#!/closelyheld-spec/1
![screenshot 2015-04-01 11 50 41](https://cloud.githubusercontent.com/assets/2028448/6934352/a4cfaf76-d865-11e4-9bd3-4bb67c871760.png)
![screenshot 2015-04-01 11 50 49](https://cloud.githubusercontent.com/assets/2028448/6934351/a471d630-d865-11e4-98fd-e85f9189dca2.png)

**Comment by audreyt** [comment]
Fixed, thanks! :rainbow:
