### ISSUE TITLE
Misc topic in each category

### ISSUE THREAD

**Issue by audreyt** [g0v/vtaiwan.tw#4]
原本是要做在對 H1 node 的回應串。
e.g. https://talk.vtaiwan.tw/t/topic/45 就會放在 https://vtaiwan.tw/#!/closelyheld/2 的大標的右側（同一列或下方）。也許作成較淡的灰色討論圖示？

**Comment by ghost** [comment]
後來 discourse 沒有開可以新增「討論話題」的設定
把其他的話題都歸類在「其他」討論話題底下
