### ISSUE TITLE
Scheduling timeline info on proposal list page

### ISSUE THREAD

**Issue by audreyt** [g0v/vtaiwan.tw#8]
In https://vtaiwan.tw/#!/proposals (among perhaps other places):
- Which phase is it in?
- How many days left in the phase?
- Stats, such as number of discussions, participants and/or views

@muan has a rather nice example from zeczec that combines separator horizontal lines with progress bar:

![2015-01-11 3 25 43](https://cloud.githubusercontent.com/assets/20723/5694596/236de5ea-99a6-11e4-9759-08d566073b1c.png)

**Comment by ghost** [comment]
proposals 會有哪些 phase?
是這裡的 https://g0v.hackpad.com/vTaiwan.tw--oWRxOF4ilfx
階段一：討論
階段二：草案
階段三：定案
嗎？

**Comment by audreyt** [comment]
是的。

**Comment by ghost** [comment]
https://speakerdeck.com/audreyt/vtaiwan-yun-zuo-liu-cheng
至少要倒數第一階段的討論到 2/28
- 版主群 2/1 才會正式開始巡
- 如果有人問到提案方的東西，7 天都是從 2/1 開始算

**Comment by audreyt** [comment]
ref: https://speakerdeck.com/audreyt/vtaiwan-yun-zuo-liu-cheng

**Comment by ghost** [comment]
修改了一下用詞，目前長這樣，有建議嗎？

![timeline-mobile](https://cloud.githubusercontent.com/assets/3395905/5987467/c3dc04a2-a965-11e4-95c9-432775313e44.png)

如果覺得在這裡呈現階段資訊（討論->草案->定案）不會太多
我想把首頁這一段三個 li 前面也加上階段名稱（分別是：討論、草案、定案）
![2015-01-31 4 26 30](https://cloud.githubusercontent.com/assets/3395905/5987471/f6ea32a6-a965-11e4-996f-0eabc56375a1.png)

@audreyt 覺得呢？

**Comment by audreyt** [comment]
好呀，當然！也可以放在 li 或 li 的 sub-li 裡，把規則講得更清楚一點點。

另外，原來「討論」/「草案」/「定案」可以點! 完全看不出來 XD 也許 :hover 時給個顏色？

(整片的提案 block 也許 :hover 時也可以給個顏色，像 .issue_item:hover 那樣。)

**Comment by ghost** [comment]
好！來加。我會參考提案 hackpad 的「運作方式」這一段，把規則寫得更清楚一點。

剛剛才做好點選的效果，所以昨天的確是還沒有點的效果（好像第一個做到一半）。XD
好啊，來加個 :hover *2。

原本的確是不確定要不要那麼明顯，想說好奇的人就會點了（咦？XD）

**Comment by yhsiang** [comment]
加 box-shadow 會不會加強想點的慾望 ?

**Comment by yhsiang** [comment]
7cb3efe2d53e3b8f2dd852a44e50eca841b41672
a5bdd79314df717f786e7e9daf9b15b7fff01cda

merged to master
